"""SQLite capabilities corresponding to ``sqlite/types.ts``."""

from collections.abc import Awaitable, Callable, Iterable
from dataclasses import dataclass
from typing import Protocol

type SqliteRow = dict[str, object]


@dataclass
class SqliteRunResult:
    changes: int | float
    last_insert_rowid: int | float | None = None


class SqliteStatement(Protocol):
    def run(self, *params: object) -> SqliteRunResult: ...
    def get(self, *params: object) -> SqliteRow | None: ...
    def all(self, *params: object) -> list[SqliteRow]: ...
    def iterate(self, *params: object) -> Iterable[SqliteRow]: ...


class SqliteDatabase(Protocol):
    def exec(self, sql: str) -> None: ...
    def prepare(self, sql: str) -> SqliteStatement: ...
    def transaction[T](self, callback: Callable[[], T]) -> T: ...
    def close(self) -> None: ...


class SqliteDatabaseFactory(Protocol):
    def open(self, path: str) -> Awaitable[SqliteDatabase]: ...
    def open_existing(self, path: str) -> Awaitable[SqliteDatabase]: ...
    def open_read_only(self, path: str) -> Awaitable[SqliteDatabase]: ...
