"""Terminal contract, separate from the platform implementation to avoid cycles."""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol


class Terminal(Protocol):
    def start(self, on_input: Callable[[str], None], on_resize: Callable[[], None]) -> None: ...

    def stop(self) -> None: ...

    async def drain_input(self, max_ms: float = 1000, idle_ms: float = 50) -> None: ...

    def write(self, data: str) -> None: ...

    @property
    def columns(self) -> int | float: ...

    @property
    def rows(self) -> int | float: ...

    @property
    def kitty_protocol_active(self) -> bool: ...

    def move_by(self, lines: int | float) -> None: ...

    def hide_cursor(self) -> None: ...

    def show_cursor(self) -> None: ...

    def clear_line(self) -> None: ...

    def clear_from_cursor(self) -> None: ...

    def clear_screen(self) -> None: ...

    def set_title(self, title: str) -> None: ...

    def set_progress(self, active: bool) -> None: ...
