"""pi-agent-core Python port.

Stateful agent with tool execution and event streaming, ported one-to-one from
``@earendil-works/pi-agent-core`` (TypeScript).

Mirrors the TypeScript package entry points:

* ``pi_agent_core`` — agent, agent-loop, harness, tools, session, compaction,
  skills, prompt templates, proxy, search, types
* ``pi_agent_core.cli`` — runnable demo program
"""

from ._pi_ai.abort import AbortController, AbortError, AbortSignal
from ._pi_ai.event_stream import (
    AssistantMessageEventStream,
    EventStream,
    create_assistant_message_event_stream,
)
from ._pi_ai.json_parse import parse_json_with_repair, parse_streaming_json, repair_json
from ._pi_ai.models import Models, Provider, calculate_cost, create_models, create_provider
from ._pi_ai.providers.anthropic import anthropic_provider, stream_anthropic
from ._pi_ai.providers.faux import (
    RegisterFauxProviderOptions,
    create_faux_core,
    faux_assistant_message,
    faux_text,
    faux_thinking,
    faux_tool_call,
)
from ._pi_ai.providers.openai_completions import openai_provider, stream_openai
from ._pi_ai.transcript import (
    create_initial_system_message,
    get_current_system_message,
    get_current_system_prompt,
    get_current_tools,
    get_tool_state_changes,
    normalize_context,
    to_tool_declaration,
)
from ._pi_ai.types import (
    AssistantMessage,
    AssistantMessageEvent,
    Cost,
    DeferredHandle,
    ImageContent,
    Message,
    Model,
    SimpleStreamOptions,
    SystemMessage,
    TextContent,
    ThinkingContent,
    Tool,
    ToolCall,
    ToolResultMessage,
    Usage,
    UserMessage,
)
from ._pi_ai.uuid_utils import uuidv7
from ._pi_ai.uuid_utils import uuidv7 as uuid7
from ._pi_ai.validation import validate_tool_arguments, validate_tool_call
from ._chord.context import (
    BACKGROUND_CONTEXT,
    TODO_CONTEXT,
    Context,
    ContextKey,
    await_with_context,
    create_context_key,
    with_abort_signal,
    with_cancel,
    with_context_value,
    without_abort_signal,
)
from .agent import Agent, AgentInitialState, AgentOptions
from .agent_loop import (
    agent_loop,
    agent_loop_continue,
    run_agent_loop,
    run_agent_loop_continue,
)
from .harness.compaction import (
    calculate_context_tokens,
    compact,
    DEFAULT_COMPACTION_SETTINGS,
    estimate_context_tokens,
    estimate_tokens,
    find_cut_point,
    find_turn_start_index,
    generate_branch_summary,
    generate_summary,
    get_last_assistant_usage,
    prepare_branch_entries,
    prepare_compaction,
    serialize_conversation,
    should_compact,
)
from .harness.messages import (
    BashExecutionMessage,
    CustomMessage,
    convert_to_llm,
    create_branch_summary_message,
    create_compaction_summary_message,
)
from .harness.prompt_templates import (
    PromptTemplate,
    format_prompt_template_invocation,
    load_prompt_templates,
    parse_command_args,
    substitute_args,
)
from .harness.result import (
    Closed,
    HarnessClosed,
    HarnessFault,
    InvalidLane,
    InvalidMessage,
    InvalidNavigation,
    LaneBusy,
    NoActiveOperation,
    NoActiveRun,
    NothingToCompact,
    NothingToResume,
    OperationMismatch,
    Result,
    ResultNamespace,
    TaggedError,
    UnknownSkill,
    UnknownTarget,
    UnknownTemplate,
    err,
    get_or_throw,
    get_or_undefined,
    match_error,
    ok,
    to_error,
)
from .harness.session import (
    Branch,
    BranchSummaryEntry,
    CommitResult,
    CompactionEntry,
    CustomEntry,
    Entry,
    EntryQuery,
    EntryStructure,
    ForkOptions,
    MemorySessionRepo,
    MemoryStorage,
    MessageEntry,
    Session,
    SessionCreateOptions,
    SessionMetadata,
    SessionRepo,
    SessionStats,
    Storage,
    UsageRow,
    branch_tip,
    lane_config,
    lane_state,
    list as list_value,
    session_name,
    value,
)
from .harness.session.context import (
    build_context_entries,
    build_session_context,
    session_entry_to_context_messages,
)
from .harness.skills import load_skills, load_sourced_skills
from .harness.system_prompt import format_skills_for_system_prompt
from .harness.events import (
    CurrentOperationInfo,
    HarnessEvent,
    LaneInfo,
    LaneQueuedItem,
    LaneSnapshot,
    LaneSnapshotTool,
    SessionSnapshot,
)
from .harness.execution import AbortRequested, create_gate
from .harness.runtime import Drive, LaneState, SliceNotImplemented, reduce_lane_snapshot
from .harness.session.jsonl import (
    JsonlSessionCreateOptions,
    JsonlSessionListOptions,
    JsonlSessionMetadata,
    JsonlSessionRepo,
    JsonlSessionRepoOptions,
    JsonlStorage,
    JsonlStorageHeader,
    JsonlStorageOptions,
    parse_jsonl_session_header,
)
from .harness.agent_harness import (
    AcquireLaneOptions,
    AgentHarnessNamespace,
    AgentHarnessOptions,
    AgentLane,
    DriveOptions,
    DriveOutcome,
    LaneExecutionInfo,
    NavigateOptions,
    OperationAdmission,
    OperationRequest,
    Resources,
    create_agent_harness,
)
from .harness.config import (
    DEFAULT_RETRY_POLICY,
    validate_compaction_settings,
    validate_retry_policy,
    validate_tool_names,
)
from .harness.execution import (
    Gate,
    apply_before_tool_decision,
    create_gate,
    create_tool_result_message,
    execute_tool_call,
    finalize_tool_call,
    prepare_tool_call,
    tool_result_from_message,
)
from .harness.hooks import HookRegistry, apply_stream_options_patch, create_stream_options_patch
from .harness.session.fork import create_fork_snapshot
from .harness.tool_adapter import default_harness_tools, harness_tool_to_agent_tool
from .harness.tools import (
    BashExecution,
    BashToolOptions,
    create_bash_tool,
    create_edit_tool,
    create_read_tool,
    create_write_tool,
)
from .harness.types import (
    AgentHarnessTool,
    BranchSummaryError,
    CompactionError,
    AgentHarnessToolInvocation,
    AgentHarnessToolUpdateOptions,
    ExecutionEnv,
    ExecutionError,
    ExecutionToolContext,
    FileError,
    FileInfo,
    FileKind,
    FileSystem,
    Shell,
    ShellExecOptions,
    ShellExecResult,
    ShellOutputCaptureOptions,
    ShellOutputLimits,
    ShellOutputMetadata,
    ShellOutputTruncation,
    ShellOutputUpdate,
    ShellOutputView,
    Skill,
)
from .harness.utils.output_capture import apply_shell_output_update, sanitize_shell_output
from .harness.utils.shell_output import execute_shell_with_capture, sanitize_binary_output
from .harness.utils.truncate import (
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_LINES,
    format_size,
    truncate_head,
    truncate_line,
    truncate_tail,
)
from .harness.utils.usage import add_usage, empty_usage
from .proxy import ProxyStreamOptions, stream_proxy
from .search import EntrySearchHit, SearchQuery, SessionSearchHit, SessionSearchService
from .stream_fn import get_default_stream_fn, set_default_stream_fn
from .types import (
    AfterToolCallContext,
    AfterToolCallResult,
    AgentContext,
    AgentEvent,
    AgentLoopConfig,
    AgentLoopTurnUpdate,
    AgentState,
    AgentTool,
    AgentToolCall,
    AgentToolResult,
    BeforeToolCallContext,
    BeforeToolCallResult,
    PrepareNextTurnContext,
    QueueMode,
    ShouldStopAfterTurnContext,
    StreamFn,
    ThinkingLevel,
    ToolExecutionMode,
)

__version__ = "0.85.1"


# ---------------------------------------------------------------------------
# Root barrel surface
# ---------------------------------------------------------------------------
#
# The TypeScript root `index.ts` re-exports the agent, loop, proxy, harness and
# telemetry surfaces. These imports keep `pi_agent_core.X` matching that same
# top-level name set; the implementations live in the modules below.
from .harness.agent_harness import AgentHarnessResources
from .harness.compaction import (
    BranchPreparation,
    BranchSummaryDetails,
    BranchSummaryResult,
    CollectEntriesResult,
    CompactResult,
    CompactionPreparation,
    FileOperations,
    GenerateBranchSummaryOptions,
    collect_entries_for_branch_summary,
    generate_summary_with_usage,
)
from .harness.config import CompactionSettings
from .harness.hooks import AgentHarnessStreamOptions, AgentHarnessStreamOptionsPatch
from .harness.telemetry import (
    AGENT_TELEMETRY_SCHEMAS,
    AI_TELEMETRY_SCHEMA,
    AiSpan,
    AiSpanAttributes,
    AiSpanEndAttributes,
    AiSpanEventAttributes,
    AiSpanEventName,
    AiSpanName,
    AiSpanStartAttributes,
    AiTelemetrySpan,
    AttributeValue,
    ExactTelemetryAttributes,
    HARNESS_TELEMETRY_SCHEMA,
    HarnessSpan,
    HarnessSpanAttributes,
    HarnessSpanEndAttributes,
    HarnessSpanEventAttributes,
    HarnessSpanEventName,
    HarnessSpanName,
    HarnessSpanStartAttributes,
    HarnessTelemetrySpan,
    InMemoryTelemetryContext,
    NOOP_TELEMETRY_CONTEXT,
    RecordedTelemetryEvent,
    RecordedTelemetrySpan,
    SchemaTelemetrySpan,
    SpanAttributes,
    SpanOptions,
    SpanStatus,
    TelemetryAttributeDefinition,
    TelemetryAttributeMetadata,
    TelemetryAttributeType,
    TelemetryContext,
    TelemetryEventAttributeDefinition,
    TelemetryEventDefinition,
    TelemetryParentDefinition,
    TelemetrySchemaDefinition,
    TelemetrySpan,
    TelemetrySpanDefinition,
    TelemetryStartAttributeDefinition,
    TypedSpanStarter,
    start_ai_span,
    start_harness_span,
)
from .harness.types import AgentHarnessToolUpdateCallback

__all__ = [
    "AGENT_TELEMETRY_SCHEMAS",
    "AI_TELEMETRY_SCHEMA",
    "AbortController",
    "AbortError",
    "AbortRequested",
    "AbortSignal",
    "AcquireLaneOptions",
    "AfterToolCallContext",
    "AfterToolCallResult",
    "Agent",
    "AgentContext",
    "AgentEvent",
    "AgentHarnessNamespace",
    "AgentHarnessOptions",
    "AgentHarnessResources",
    "AgentHarnessStreamOptions",
    "AgentHarnessStreamOptionsPatch",
    "AgentHarnessTool",
    "AgentHarnessToolInvocation",
    "AgentHarnessToolUpdateCallback",
    "AgentHarnessToolUpdateOptions",
    "AgentInitialState",
    "AgentLane",
    "AgentLoopConfig",
    "AgentLoopTurnUpdate",
    "AgentOptions",
    "AgentState",
    "AgentTool",
    "AgentToolCall",
    "AgentToolResult",
    "AiSpan",
    "AiSpanAttributes",
    "AiSpanEndAttributes",
    "AiSpanEventAttributes",
    "AiSpanEventName",
    "AiSpanName",
    "AiSpanStartAttributes",
    "AiTelemetrySpan",
    "AssistantMessage",
    "AssistantMessageEvent",
    "AssistantMessageEventStream",
    "AttributeValue",
    "BACKGROUND_CONTEXT",
    "BashExecution",
    "BashExecutionMessage",
    "BashToolOptions",
    "BeforeToolCallContext",
    "BeforeToolCallResult",
    "Branch",
    "BranchPreparation",
    "BranchSummaryDetails",
    "BranchSummaryEntry",
    "BranchSummaryError",
    "BranchSummaryResult",
    "Closed",
    "CollectEntriesResult",
    "CommitResult",
    "CompactResult",
    "CompactionEntry",
    "CompactionError",
    "CompactionPreparation",
    "CompactionSettings",
    "Context",
    "ContextKey",
    "Cost",
    "CurrentOperationInfo",
    "CustomEntry",
    "CustomMessage",
    "DEFAULT_COMPACTION_SETTINGS",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_LINES",
    "DEFAULT_RETRY_POLICY",
    "DeferredHandle",
    "Drive",
    "DriveOptions",
    "DriveOutcome",
    "Entry",
    "EntryQuery",
    "EntrySearchHit",
    "EntryStructure",
    "EventStream",
    "ExactTelemetryAttributes",
    "ExecutionEnv",
    "ExecutionError",
    "ExecutionToolContext",
    "FileError",
    "FileInfo",
    "FileKind",
    "FileOperations",
    "FileSystem",
    "ForkOptions",
    "Gate",
    "GenerateBranchSummaryOptions",
    "HARNESS_TELEMETRY_SCHEMA",
    "HarnessClosed",
    "HarnessEvent",
    "HarnessFault",
    "HarnessSpan",
    "HarnessSpanAttributes",
    "HarnessSpanEndAttributes",
    "HarnessSpanEventAttributes",
    "HarnessSpanEventName",
    "HarnessSpanName",
    "HarnessSpanStartAttributes",
    "HarnessTelemetrySpan",
    "HookRegistry",
    "ImageContent",
    "InMemoryTelemetryContext",
    "InvalidLane",
    "InvalidMessage",
    "InvalidNavigation",
    "JsonlSessionCreateOptions",
    "JsonlSessionListOptions",
    "JsonlSessionMetadata",
    "JsonlSessionRepo",
    "JsonlSessionRepoOptions",
    "JsonlStorage",
    "JsonlStorageHeader",
    "JsonlStorageOptions",
    "LaneBusy",
    "LaneExecutionInfo",
    "LaneInfo",
    "LaneQueuedItem",
    "LaneSnapshot",
    "LaneSnapshotTool",
    "LaneState",
    "MemorySessionRepo",
    "MemoryStorage",
    "Message",
    "MessageEntry",
    "Model",
    "Models",
    "NOOP_TELEMETRY_CONTEXT",
    "NavigateOptions",
    "NoActiveOperation",
    "NoActiveRun",
    "NothingToCompact",
    "NothingToResume",
    "OperationAdmission",
    "OperationMismatch",
    "OperationRequest",
    "PrepareNextTurnContext",
    "PromptTemplate",
    "Provider",
    "ProxyStreamOptions",
    "QueueMode",
    "RecordedTelemetryEvent",
    "RecordedTelemetrySpan",
    "RegisterFauxProviderOptions",
    "Resources",
    "Result",
    "ResultNamespace",
    "SchemaTelemetrySpan",
    "SearchQuery",
    "Session",
    "SessionCreateOptions",
    "SessionMetadata",
    "SessionRepo",
    "SessionSearchHit",
    "SessionSearchService",
    "SessionSnapshot",
    "SessionStats",
    "Shell",
    "ShellExecOptions",
    "ShellExecResult",
    "ShellOutputCaptureOptions",
    "ShellOutputLimits",
    "ShellOutputMetadata",
    "ShellOutputTruncation",
    "ShellOutputUpdate",
    "ShellOutputView",
    "ShouldStopAfterTurnContext",
    "SimpleStreamOptions",
    "Skill",
    "SliceNotImplemented",
    "SpanAttributes",
    "SpanOptions",
    "SpanStatus",
    "Storage",
    "StreamFn",
    "SystemMessage",
    "TODO_CONTEXT",
    "TaggedError",
    "TelemetryAttributeDefinition",
    "TelemetryAttributeMetadata",
    "TelemetryAttributeType",
    "TelemetryContext",
    "TelemetryEventAttributeDefinition",
    "TelemetryEventDefinition",
    "TelemetryParentDefinition",
    "TelemetrySchemaDefinition",
    "TelemetrySpan",
    "TelemetrySpanDefinition",
    "TelemetryStartAttributeDefinition",
    "TextContent",
    "ThinkingContent",
    "ThinkingLevel",
    "Tool",
    "ToolCall",
    "ToolExecutionMode",
    "ToolResultMessage",
    "TypedSpanStarter",
    "UnknownSkill",
    "UnknownTarget",
    "UnknownTemplate",
    "Usage",
    "UsageRow",
    "UserMessage",
    "add_usage",
    "agent_loop",
    "agent_loop_continue",
    "anthropic_provider",
    "apply_before_tool_decision",
    "apply_shell_output_update",
    "apply_stream_options_patch",
    "await_with_context",
    "branch_tip",
    "build_context_entries",
    "build_session_context",
    "calculate_context_tokens",
    "calculate_cost",
    "collect_entries_for_branch_summary",
    "compact",
    "convert_to_llm",
    "create_agent_harness",
    "create_assistant_message_event_stream",
    "create_bash_tool",
    "create_branch_summary_message",
    "create_compaction_summary_message",
    "create_context_key",
    "create_edit_tool",
    "create_faux_core",
    "create_fork_snapshot",
    "create_gate",
    "create_initial_system_message",
    "create_models",
    "create_provider",
    "create_read_tool",
    "create_stream_options_patch",
    "create_tool_result_message",
    "create_write_tool",
    "default_harness_tools",
    "empty_usage",
    "err",
    "estimate_context_tokens",
    "estimate_tokens",
    "execute_shell_with_capture",
    "execute_tool_call",
    "faux_assistant_message",
    "faux_text",
    "faux_thinking",
    "faux_tool_call",
    "finalize_tool_call",
    "find_cut_point",
    "find_turn_start_index",
    "format_prompt_template_invocation",
    "format_size",
    "format_skills_for_system_prompt",
    "generate_branch_summary",
    "generate_summary",
    "generate_summary_with_usage",
    "get_current_system_message",
    "get_current_system_prompt",
    "get_current_tools",
    "get_default_stream_fn",
    "get_last_assistant_usage",
    "get_or_throw",
    "get_or_undefined",
    "get_tool_state_changes",
    "harness_tool_to_agent_tool",
    "lane_config",
    "lane_state",
    "list_value",
    "load_prompt_templates",
    "load_skills",
    "load_sourced_skills",
    "match_error",
    "normalize_context",
    "ok",
    "openai_provider",
    "parse_command_args",
    "parse_json_with_repair",
    "parse_jsonl_session_header",
    "parse_streaming_json",
    "prepare_branch_entries",
    "prepare_compaction",
    "prepare_tool_call",
    "reduce_lane_snapshot",
    "repair_json",
    "run_agent_loop",
    "run_agent_loop_continue",
    "sanitize_binary_output",
    "sanitize_shell_output",
    "serialize_conversation",
    "session_entry_to_context_messages",
    "session_name",
    "set_default_stream_fn",
    "should_compact",
    "start_ai_span",
    "start_harness_span",
    "stream_anthropic",
    "stream_openai",
    "stream_proxy",
    "substitute_args",
    "to_error",
    "to_tool_declaration",
    "tool_result_from_message",
    "truncate_head",
    "truncate_line",
    "truncate_tail",
    "uuid7",
    "uuidv7",
    "validate_compaction_settings",
    "validate_retry_policy",
    "validate_tool_arguments",
    "validate_tool_call",
    "validate_tool_names",
    "value",
    "with_abort_signal",
    "with_cancel",
    "with_context_value",
    "without_abort_signal",
]
