"""Vendor-neutral telemetry, explicit parent contexts, and schema utilities."""

from .memory import InMemoryTelemetryContext
from .noop import NOOP_TELEMETRY_CONTEXT
from .schema import create_typed_span_starter, define_telemetry_schema
from .types import (
    AttributeValue,
    ExactTelemetryAttributes,
    InferEventAttributes,
    InferOptionalAttributes,
    InferRequiredAndOptionalAttributes,
    InferStartAttributes,
    RecordedTelemetryEvent,
    RecordedTelemetrySpan,
    SchemaTelemetrySpan,
    SpanAttributes,
    SpanCallback,
    SpanError,
    SpanOptions,
    SpanStatus,
    TelemetryAttributeDefinition,
    TelemetryAttributeMetadata,
    TelemetryAttributeType,
    TelemetryContext,
    TelemetryEventAttributeDefinition,
    TelemetryEventDefinition,
    TelemetryParentDefinition,
    TelemetrySchemaDefinition,
    TelemetrySchemaSpanEndAttributes,
    TelemetrySchemaSpanEventAttributes,
    TelemetrySchemaSpanEventName,
    TelemetrySchemaSpanName,
    TelemetrySchemaSpanStartAttributes,
    TelemetrySchemaSpanUnion,
    TelemetrySpan,
    TelemetrySpanDefinition,
    TelemetrySpanStatusDefinition,
    TelemetryStartAttributeDefinition,
    TypedSpanCallback,
    TypedSpanStarter,
)

__all__ = [
    "AttributeValue",
    "ExactTelemetryAttributes",
    "InferEventAttributes",
    "InferOptionalAttributes",
    "InferRequiredAndOptionalAttributes",
    "InferStartAttributes",
    "InMemoryTelemetryContext",
    "NOOP_TELEMETRY_CONTEXT",
    "RecordedTelemetryEvent",
    "RecordedTelemetrySpan",
    "SchemaTelemetrySpan",
    "SpanAttributes",
    "SpanCallback",
    "SpanError",
    "SpanOptions",
    "SpanStatus",
    "TelemetryAttributeDefinition",
    "TelemetryAttributeMetadata",
    "TelemetryAttributeType",
    "TelemetryContext",
    "TelemetryEventAttributeDefinition",
    "TelemetryEventDefinition",
    "TelemetryParentDefinition",
    "TelemetrySchemaDefinition",
    "TelemetrySchemaSpanEndAttributes",
    "TelemetrySchemaSpanEventAttributes",
    "TelemetrySchemaSpanEventName",
    "TelemetrySchemaSpanName",
    "TelemetrySchemaSpanStartAttributes",
    "TelemetrySchemaSpanUnion",
    "TelemetrySpan",
    "TelemetrySpanDefinition",
    "TelemetrySpanStatusDefinition",
    "TelemetryStartAttributeDefinition",
    "TypedSpanCallback",
    "TypedSpanStarter",
    "create_typed_span_starter",
    "define_telemetry_schema",
]
